namespace Gsemac.Net.Curl {

    public enum CurlCode {
        OK,
        UnsupportedProtocol,
        FailedInit,
        UrlMalformat,
        NotBuiltIn,
        CouldntResolveProxy,
        CouldntResolveHost,
        CouldntConnect,
        WeirdServerReply,
        RemoteAccessDenied,
        FtpAcceptFailed,
        WeirdPassReply,
        FtpAcceptTimeout,
        FtpWeirdPasvReply,
        FtpWeird227Format,
        FtpCantGetHost,
        Http2,
        FptCouldntSetType,
        PartialFile,
        CouldntRetrFile,
        QuoteError = 21,
        HttpReturnedError,
        WriteError,
        UploadFailed = 25,
        ReadError,
        OutOfMemory,
        OperationTimeout,
        FtpPortFailed = 30,
        FtpCouldntUseRest,
        RangeError = 33,
        HttpPostError,
        SslConnectError,
        BadDownloadResume,
        FileCouldntReadFile,
        LdapCannotBind,
        LdapSearchFailed,
        FunctionNotFound = 41,
        AbortedByCallback,
        BadFunctionArgument,
        InterfaceFailed = 45,
        TooManyRedirects = 47,
        UnknownOption,
        TelnetOptionSyntax,
        GotNothing = 52,
        SslEngineNotFound,
        SslEngineSetFailed,
        SendError,
        RecvError,
        SslCertProblem = 58,
        SslCipher,
        PeerFailedVerification,
        BadContentEncoding,
        LdapInvalidUrl,
        FilesizeExceeded,
        UseSslFailed,
        SendFailRewind,
        SslEngineInitFailed,
        LoginDenied,
        TftpNotFound,
        TftpPerm,
        RemoteDiskFull,
        TftpIllegal,
        TftpUnknownId,
        RemoteFileExists,
        TftpNoSuchUser,
        ConvFailed,
        ConvReqd,
        SslCacertBadFile,
        RemoteFileNotFound,
        Ssh,
        SslShutdownFailed,
        Again,
        SslCrlBadFile,
        SslIssuerError,
        FtpPretFailed,
        RtspCseqError,
        RtspSessionError,
        FtpBadFileList,
        ChunkFailed,
        NoConnectionAvailable,
        SslPinnedPubKeyNotMatch,
        SslInvalidCertStatus,
        Http2Stream,
        RecursiveApiCall,
        AuthError,
        Http3,
        QuicConnectError
    }

}