//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsemac.Net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gsemac.Net.Properties.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot handle redirect from HTTP/HTTPS protocols to other dissimilar ones..
        /// </summary>
        internal static string CannotRedirectToDissimilarProtocols {
            get {
                return ResourceManager.GetString("CannotRedirectToDissimilarProtocols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Content-Length value must be greater than or equal to zero..
        /// </summary>
        internal static string ContentLengthMustBeGreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("ContentLengthMustBeGreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP listener timed out while waiting for a request..
        /// </summary>
        internal static string HttpListenerTimedOut {
            get {
                return ResourceManager.GetString("HttpListenerTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inner handler has not been set..
        /// </summary>
        internal static string InnerHandlerHasNotBeenSet {
            get {
                return ResourceManager.GetString("InnerHandlerHasNotBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given cookie domain pattern is invalid..
        /// </summary>
        internal static string InvalidCookieDomainPattern {
            get {
                return ResourceManager.GetString("InvalidCookieDomainPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string is not a valid HTTP header..
        /// </summary>
        internal static string InvalidHttpHeader {
            get {
                return ResourceManager.GetString("InvalidHttpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid HTTP header..
        /// </summary>
        internal static string InvalidHttpHeaderWithString {
            get {
                return ResourceManager.GetString("InvalidHttpHeaderWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; is not a valid HTTP refresh header..
        /// </summary>
        internal static string InvalidHttpRefreshHeaderWithString {
            get {
                return ResourceManager.GetString("InvalidHttpRefreshHeaderWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string is not a valid HTTP request line..
        /// </summary>
        internal static string InvalidHttpRequestLine {
            get {
                return ResourceManager.GetString("InvalidHttpRequestLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given string is not a valid HTTP status line..
        /// </summary>
        internal static string InvalidHttpStatusLine {
            get {
                return ResourceManager.GetString("InvalidHttpStatusLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data URL is malformed..
        /// </summary>
        internal static string MalformedDataUrl {
            get {
                return ResourceManager.GetString("MalformedDataUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date header &apos;{0}&apos; was malformed..
        /// </summary>
        internal static string MalformedDateHeader {
            get {
                return ResourceManager.GetString("MalformedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is malformed..
        /// </summary>
        internal static string MalformedUrl {
            get {
                return ResourceManager.GetString("MalformedUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method must be POST or PUT..
        /// </summary>
        internal static string MethodMustBePostOrPut {
            get {
                return ResourceManager.GetString("MethodMustBePostOrPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was aborted: The request was canceled..
        /// </summary>
        internal static string RequestCanceled {
            get {
                return ResourceManager.GetString("RequestCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scheme contains invalid characters..
        /// </summary>
        internal static string SchemeContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("SchemeContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server returned an error: {0}..
        /// </summary>
        internal static string TheRemoteServerReturnedAnErrorWithStatusCode {
            get {
                return ResourceManager.GetString("TheRemoteServerReturnedAnErrorWithStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many automatic redirections were attempted..
        /// </summary>
        internal static string TooManyAutomaticRedirections {
            get {
                return ResourceManager.GetString("TooManyAutomaticRedirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `WebResponse` is not an instance of `HttpWebResponse`..
        /// </summary>
        internal static string WebResponseWasNotAnInstanceOfHttpWebResponse {
            get {
                return ResourceManager.GetString("WebResponseWasNotAnInstanceOfHttpWebResponse", resourceCulture);
            }
        }
    }
}
